import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { Providers } from "./providers";
import { AppbarClient } from "@/components/AppbarClient";
const geist = Geist({ subsets: ["latin"] });
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      
        
        <body className={geist.className}>
          <Providers>
            <Toaster position="bottom-right"></Toaster>
            <AppbarClient></AppbarClient>
            {children}
          </Providers>
        </body>
    </html>
  );
}
